gen-file: ./data/test.bin
external-file:
  - ./data/file1
  - ./data/file2
create-method: default
operation:
  - action: syscall
    call: sys_write
    data: "\x68\x65\x6c\x6c\x6f\x20\x77\x6f\x72\x6c\x64" # hello world
    len: 11
  - action: write
    verb: file
    filename: ./data/file1
    offset: 0
    len: 1024
  - action: write
    verb: random
    len: 1024